name: Build Kernel

on:
  push:
    branches: [main]

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Kernel
        run: |
          mkdir android-kernel
          cd android-kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b android-msm-crosshatch-4.9-android12
          repo sync -j$(nproc)
          cd kernel
          make O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- CC=clang-${CLANG_VERSION} -j$(nproc)
